Create database DB_Examen3

Go 

Use DB_Examen3

Go 

Create Table Encuesta 
(

ID int identity,
Nombre varchar(50) NOT NULL,
Edad int,
CorreoElectronico varchar (50)NOT NULL, 
Partido varchar(50) NOT NULL,
CONSTRAINT pk_IDencuesta PRIMARY KEY(ID)


)

Go 


Create Table Partidos 
(

PartidoID int identity,
Descripcion varchar(50) NOT NULL,
IDencuesta int,
CONSTRAINT fk_IDencuesta FOREIGN KEY(IDencuesta) REFERENCES Encuesta(ID),
CONSTRAINT pk_IDpartidos PRIMARY KEY(PartidoID)


)

Go 

--- STORE PROCEDURES ---- USUARIOS

CREATE PROCEDURE CONSULTARENCUESTA
AS
BEGIN
SELECT * FROM Encuesta

END 

CREATE PROCEDURE BORRARENCUESTA 
@CODIGO INT
AS
BEGIN
DELETE Encuesta WHERE ID = @CODIGO

END 

CREATE PROCEDURE CONSULTAR_FILTROENCUESTA
@CODIGO INT
AS
BEGIN
SELECT * FROM Encuesta WHERE ID = @CODIGO

END 

CREATE PROCEDURE ACTUALIZARENCUESTA
@ID INT,
@NOMBRE VARCHAR (50),
@EDAD int,
@CORREO VARCHAR (50),
@PARTIDO VARCHAR (50)

AS

BEGIN
UPDATE Encuesta SET Nombre = @NOMBRE, Edad= @EDAD, CorreoElectronico = @CORREO, Partido=@PARTIDO where ID = @ID 

END 


CREATE PROCEDURE AGREGARENCUESTA
@NOMBRE VARCHAR (50),
@EDAD INT,
@CORREO VARCHAR (50),
@PARTIDO VARCHAR (50)

AS
BEGIN

INSERT INTO Encuesta (Nombre,Edad, CorreoElectronico,Partido) VALUES (@NOMBRE, @EDAD, @CORREO,@PARTIDO)

END

INSERT INTO Encuesta (Nombre,Edad, CorreoElectronico, Partido) VALUES ('PEDRO MASIS', '25', 'MASIS.PEDRO@GMAIL.COM','PLN')

------------------------------------ PARTIDOS

CREATE PROCEDURE CONSULTARPARTIDOS
AS
BEGIN
SELECT * FROM Partidos

END 

CREATE PROCEDURE BORRARPARTIDOS
@CODIGO INT
AS
BEGIN
DELETE Partidos WHERE PartidoID = @CODIGO

END 

CREATE PROCEDURE CONSULTAR_FILTROPARTIDOS
@CODIGO INT
AS
BEGIN
SELECT * FROM Partidos WHERE PartidoID = @CODIGO

END 

CREATE PROCEDURE ACTUALIZARPARTIDOS
@ID INT,
@DESCRIPCION VARCHAR (50)


AS
BEGIN
UPDATE Partidos SET Descripcion = @DESCRIPCION WHERE PartidoID = @ID 

END 

CREATE PROCEDURE AGREGARPARTIDOS
@DESCRIPCION VARCHAR (50)


AS
BEGIN

INSERT INTO Partidos (Descripcion) VALUES (@DESCRIPCION)

END


INSERT INTO Partidos (Descripcion) VALUES ('PLN' )
